# Generated by Django 4.0.5 on 2022-06-29 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphs',
            name='upload',
            field=models.FileField(upload_to='csv_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv,xls,xlsx'])]),
        ),
    ]
