# Generated by Django 3.2.6 on 2022-06-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_graphs_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphs',
            name='upload',
            field=models.FileField(upload_to='media/graphs'),
        ),
    ]
