# Generated by Django 4.0.5 on 2022-06-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_password1_newuser_confirm_password_and_more'),
        ('home', '0003_alter_graphs_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
            ],
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
    ]
