# Generated by Django 3.2.6 on 2022-06-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.institution'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='normal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.normaluser', verbose_name='user'),
        ),
    ]
