# Generated by Django 3.2.6 on 2022-06-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220625_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='confirm_pass',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
