# Generated by Django 4.0.5 on 2022-06-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_password1_newuser_confirm_password_and_more'),
        ('home', '0004_supervisor_delete_normaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.supervisor', verbose_name='supervisor'),
        ),
    ]
