# Generated by Django 3.2.6 on 2022-06-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220625_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='password2',
            field=models.CharField(default=3, max_length=150),
            preserve_default=False,
        ),
    ]
