# Generated by Django 3.2.6 on 2022-06-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_newuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='password2',
        ),
    ]
