# Generated by Django 3.2.6 on 2022-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_newuser_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='password1',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
